# 构建容器
FROM node:16 as build
WORKDIR /app
RUN npm install vue@latest
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# 生产容器
FROM nginx:1.16.0-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]